pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'make -C main'
            }
        }
        stage('Test') {
            steps {
                sh 'make -C main test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'make deploy'
            }
        }
    }
    post {
        always {
            sh 'make -C main clean'
        }
        failure {
            echo 'pipeline failed'
        }
    }
}
